apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "tmp.fullname" . }}-manager-role
  labels:
  {{- include "tmp.labels" . | nindent 4 }}
rules:
- apiGroups:
  - hub.kalypso.io
  resources:
  - azureresourcegraphs
  - deploymentdescriptors
  - reconcilers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - hub.kalypso.io
  resources:
  - azureresourcegraphs/finalizers
  - deploymentdescriptors/finalizers
  - reconcilers/finalizers
  verbs:
  - update
- apiGroups:
  - hub.kalypso.io
  resources:
  - azureresourcegraphs/status
  - deploymentdescriptors/status
  - reconcilers/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - kustomize.toolkit.fluxcd.io
  resources:
  - kustomizations
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "tmp.fullname" . }}-manager-rolebinding
  labels:
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: kalypso-observability-hub
    app.kubernetes.io/part-of: kalypso-observability-hub
  {{- include "tmp.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: '{{ include "tmp.fullname" . }}-manager-role'
subjects:
- kind: ServiceAccount
  name: '{{ include "tmp.fullname" . }}-controller-manager'
  namespace: '{{ .Release.Namespace }}'