apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "tmp.fullname" . }}-secret-viewer-role
  labels:
  {{- include "tmp.labels" . | nindent 4 }}
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  - secrets
  verbs:
  - get
  - watch
  - list
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "tmp.fullname" . }}-secret-viewer-rolebinding
  labels:
  {{- include "tmp.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: '{{ include "tmp.fullname" . }}-secret-viewer-role'
subjects:
- kind: ServiceAccount
  name: '{{ include "tmp.fullname" . }}-controller-manager'
  namespace: '{{ .Release.Namespace }}'