neo4j:
  name: "my-cluster"
  minimumClusterSize: 1
  resources:
    cpu: "0.5"
    memory: "2Gi"
  password: "" # <-- Change this to your own password #gitleaks:allow
  acceptLicenseAgreement: "yes"

volumes:
  data:
    mode: "dynamic"
    dynamic:
      # * managed-csi-premium provisions premium SSD disks (recommended)
      # * managed-csi provisions standard SSD backed disks
      storageClassName: managed-csi