// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.21.9
// source: storage.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// StorageApiClient is the client API for StorageApi service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type StorageApiClient interface {
	UpdateWorkspace(ctx context.Context, in *Workspace, opts ...grpc.CallOption) (*Workspace, error)
}

type storageApiClient struct {
	cc grpc.ClientConnInterface
}

func NewStorageApiClient(cc grpc.ClientConnInterface) StorageApiClient {
	return &storageApiClient{cc}
}

func (c *storageApiClient) UpdateWorkspace(ctx context.Context, in *Workspace, opts ...grpc.CallOption) (*Workspace, error) {
	out := new(Workspace)
	err := c.cc.Invoke(ctx, "/api.StorageApi/UpdateWorkspace", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// StorageApiServer is the server API for StorageApi service.
// All implementations must embed UnimplementedStorageApiServer
// for forward compatibility
type StorageApiServer interface {
	UpdateWorkspace(context.Context, *Workspace) (*Workspace, error)
	mustEmbedUnimplementedStorageApiServer()
}

// UnimplementedStorageApiServer must be embedded to have forward compatible implementations.
type UnimplementedStorageApiServer struct {
}

func (UnimplementedStorageApiServer) UpdateWorkspace(context.Context, *Workspace) (*Workspace, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateWorkspace not implemented")
}
func (UnimplementedStorageApiServer) mustEmbedUnimplementedStorageApiServer() {}

// UnsafeStorageApiServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to StorageApiServer will
// result in compilation errors.
type UnsafeStorageApiServer interface {
	mustEmbedUnimplementedStorageApiServer()
}

func RegisterStorageApiServer(s grpc.ServiceRegistrar, srv StorageApiServer) {
	s.RegisterService(&StorageApi_ServiceDesc, srv)
}

func _StorageApi_UpdateWorkspace_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Workspace)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StorageApiServer).UpdateWorkspace(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.StorageApi/UpdateWorkspace",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StorageApiServer).UpdateWorkspace(ctx, req.(*Workspace))
	}
	return interceptor(ctx, in, info, handler)
}

// StorageApi_ServiceDesc is the grpc.ServiceDesc for StorageApi service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var StorageApi_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "api.StorageApi",
	HandlerType: (*StorageApiServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "UpdateWorkspace",
			Handler:    _StorageApi_UpdateWorkspace_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "storage.proto",
}
